// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model.Repositories;

namespace Model.Migrations
{
    [DbContext(typeof(EFEindproefContext))]
    [Migration("20210121133420_Wijzigen Bericht")]
    partial class WijzigenBericht
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Model.Entities.Adres", b =>
                {
                    b.Property<int>("AdresId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<byte[]>("Aangepast")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("BusNr")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("HuisNr")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("StraatId")
                        .HasColumnType("int");

                    b.HasKey("AdresId");

                    b.HasIndex("StraatId", "HuisNr", "BusNr")
                        .IsUnique()
                        .HasFilter("[BusNr] IS NOT NULL");

                    b.ToTable("Adressen");

                    b.HasData(
                        new
                        {
                            AdresId = 1,
                            HuisNr = "1",
                            StraatId = 1
                        },
                        new
                        {
                            AdresId = 2,
                            HuisNr = "2",
                            StraatId = 2
                        },
                        new
                        {
                            AdresId = 3,
                            BusNr = "1",
                            HuisNr = "3a",
                            StraatId = 3
                        },
                        new
                        {
                            AdresId = 4,
                            BusNr = "2",
                            HuisNr = "4",
                            StraatId = 4
                        },
                        new
                        {
                            AdresId = 5,
                            BusNr = "3",
                            HuisNr = "5b",
                            StraatId = 5
                        },
                        new
                        {
                            AdresId = 6,
                            HuisNr = "6",
                            StraatId = 6
                        });
                });

            modelBuilder.Entity("Model.Entities.Afdeling", b =>
                {
                    b.Property<int>("AfdelingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("AfdelingCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("AfdelingNaam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AfdelingTekst")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("AfdelingId");

                    b.HasIndex("AfdelingCode")
                        .IsUnique();

                    b.HasIndex("AfdelingNaam")
                        .IsUnique();

                    b.ToTable("Afdelingen");

                    b.HasData(
                        new
                        {
                            AfdelingId = 1,
                            AfdelingCode = "VERK",
                            AfdelingNaam = "Verkoop"
                        },
                        new
                        {
                            AfdelingId = 2,
                            AfdelingCode = "BOEK",
                            AfdelingNaam = "Boekhouding"
                        },
                        new
                        {
                            AfdelingId = 3,
                            AfdelingCode = "AANK",
                            AfdelingNaam = "Aankoop"
                        });
                });

            modelBuilder.Entity("Model.Entities.Bericht", b =>
                {
                    b.Property<int>("BerichtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("BerichtTekst")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("BerichtTijdstip")
                        .HasColumnType("datetime2");

                    b.Property<string>("BerichtTitel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("BerichtTypeId")
                        .HasColumnType("int");

                    b.Property<int>("GemeenteId")
                        .HasColumnType("int");

                    b.Property<int?>("HoofdBerichtId")
                        .HasColumnType("int");

                    b.Property<int>("PersoonId")
                        .HasColumnType("int");

                    b.Property<int?>("ProfielPersoonId")
                        .HasColumnType("int");

                    b.HasKey("BerichtId");

                    b.HasIndex("BerichtTypeId");

                    b.HasIndex("GemeenteId");

                    b.HasIndex("HoofdBerichtId");

                    b.HasIndex("PersoonId");

                    b.HasIndex("ProfielPersoonId");

                    b.ToTable("Berichten");
                });

            modelBuilder.Entity("Model.Entities.BerichtType", b =>
                {
                    b.Property<int>("BerichtTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("BerichtTypeCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("BerichtTypeNaam")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BerichtTypeTekst")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BerichtTypeId");

                    b.HasIndex("BerichtTypeCode")
                        .IsUnique();

                    b.ToTable("BerichtTypes");

                    b.HasData(
                        new
                        {
                            BerichtTypeId = 1,
                            BerichtTypeCode = "AL",
                            BerichtTypeNaam = "Algemeen"
                        },
                        new
                        {
                            BerichtTypeId = 2,
                            BerichtTypeCode = "TK",
                            BerichtTypeNaam = "Te Koop"
                        },
                        new
                        {
                            BerichtTypeId = 3,
                            BerichtTypeCode = "IZ",
                            BerichtTypeNaam = "Ik zoek"
                        },
                        new
                        {
                            BerichtTypeId = 4,
                            BerichtTypeCode = "ID",
                            BerichtTypeNaam = "Idee"
                        },
                        new
                        {
                            BerichtTypeId = 5,
                            BerichtTypeCode = "LN",
                            BerichtTypeNaam = "Lenen"
                        },
                        new
                        {
                            BerichtTypeId = 6,
                            BerichtTypeCode = "WG",
                            BerichtTypeNaam = "Weggeven"
                        },
                        new
                        {
                            BerichtTypeId = 7,
                            BerichtTypeCode = "AC",
                            BerichtTypeNaam = "Activiteit"
                        },
                        new
                        {
                            BerichtTypeId = 8,
                            BerichtTypeCode = "MD",
                            BerichtTypeNaam = "Melding"
                        },
                        new
                        {
                            BerichtTypeId = 9,
                            BerichtTypeCode = "BS",
                            BerichtTypeNaam = "Babysit"
                        },
                        new
                        {
                            BerichtTypeId = 10,
                            BerichtTypeCode = "HD",
                            BerichtTypeNaam = "Huishouden"
                        },
                        new
                        {
                            BerichtTypeId = 11,
                            BerichtTypeCode = "GH",
                            BerichtTypeNaam = "Gezondheid"
                        });
                });

            modelBuilder.Entity("Model.Entities.Gemeente", b =>
                {
                    b.Property<int>("GemeenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("GemeenteNaam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("HoofdGemeenteId")
                        .HasColumnType("int");

                    b.Property<int>("PostCode")
                        .HasColumnType("int");

                    b.Property<int>("ProvincieId")
                        .HasColumnType("int");

                    b.Property<int>("TaalId")
                        .HasColumnType("int");

                    b.HasKey("GemeenteId");

                    b.HasIndex("GemeenteNaam")
                        .IsUnique();

                    b.HasIndex("HoofdGemeenteId");

                    b.HasIndex("ProvincieId");

                    b.HasIndex("TaalId");

                    b.ToTable("Gemeentes");

                    b.HasData(
                        new
                        {
                            GemeenteId = 1730,
                            GemeenteNaam = "Beernem",
                            PostCode = 8730,
                            ProvincieId = 5,
                            TaalId = 1
                        },
                        new
                        {
                            GemeenteId = 1731,
                            GemeenteNaam = "Oedelem",
                            HoofdGemeenteId = 1730,
                            PostCode = 8730,
                            ProvincieId = 5,
                            TaalId = 1
                        },
                        new
                        {
                            GemeenteId = 1732,
                            GemeenteNaam = "Sint-Joris",
                            HoofdGemeenteId = 1730,
                            PostCode = 8730,
                            ProvincieId = 5,
                            TaalId = 1
                        },
                        new
                        {
                            GemeenteId = 1790,
                            GemeenteNaam = "Oostkamp",
                            PostCode = 8020,
                            ProvincieId = 5,
                            TaalId = 1
                        },
                        new
                        {
                            GemeenteId = 1791,
                            GemeenteNaam = "Herstberge",
                            HoofdGemeenteId = 1790,
                            PostCode = 8020,
                            ProvincieId = 5,
                            TaalId = 1
                        },
                        new
                        {
                            GemeenteId = 1792,
                            GemeenteNaam = "Ruddervoorde",
                            HoofdGemeenteId = 1790,
                            PostCode = 8020,
                            ProvincieId = 5,
                            TaalId = 1
                        },
                        new
                        {
                            GemeenteId = 1793,
                            GemeenteNaam = "Waardamme",
                            HoofdGemeenteId = 1790,
                            PostCode = 8020,
                            ProvincieId = 5,
                            TaalId = 1
                        });
                });

            modelBuilder.Entity("Model.Entities.InteresseSoort", b =>
                {
                    b.Property<int>("IntersseSoortId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("InteresseSoortNaam")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IntersseSoortId");

                    b.HasIndex("InteresseSoortNaam")
                        .IsUnique();

                    b.ToTable("InteresseSoorten");

                    b.HasData(
                        new
                        {
                            IntersseSoortId = 1,
                            InteresseSoortNaam = "Fietsen"
                        },
                        new
                        {
                            IntersseSoortId = 2,
                            InteresseSoortNaam = "ICT"
                        },
                        new
                        {
                            IntersseSoortId = 3,
                            InteresseSoortNaam = "Klussen"
                        },
                        new
                        {
                            IntersseSoortId = 4,
                            InteresseSoortNaam = "Muziek"
                        },
                        new
                        {
                            IntersseSoortId = 5,
                            InteresseSoortNaam = "Muziek spelen"
                        },
                        new
                        {
                            IntersseSoortId = 6,
                            InteresseSoortNaam = "Natuur"
                        },
                        new
                        {
                            IntersseSoortId = 7,
                            InteresseSoortNaam = "TV"
                        },
                        new
                        {
                            IntersseSoortId = 8,
                            InteresseSoortNaam = "Vrijwilliegrswerk"
                        },
                        new
                        {
                            IntersseSoortId = 9,
                            InteresseSoortNaam = "Wandelen"
                        },
                        new
                        {
                            IntersseSoortId = 10,
                            InteresseSoortNaam = "Zwemmen"
                        });
                });

            modelBuilder.Entity("Model.Entities.Persoon", b =>
                {
                    b.Property<int>("PersoonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<byte[]>("Aangepast")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("AdresId")
                        .HasColumnType("int");

                    b.Property<string>("FamilieNaam")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("Geblokkeerd")
                        .HasColumnType("bit");

                    b.Property<DateTime>("GeboorteDatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("GeboorteplaatsId")
                        .HasColumnType("int");

                    b.Property<int>("GeslachtType")
                        .HasColumnType("int");

                    b.Property<int>("LoginAantal")
                        .HasColumnType("int");

                    b.Property<string>("LoginNaam")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LoginPaswoord")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PersoonType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaalId")
                        .HasColumnType("int");

                    b.Property<string>("TelefoonNr")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("VerkeerdeLoginsAantal")
                        .HasColumnType("int");

                    b.Property<string>("VoorNaam")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PersoonId");

                    b.HasIndex("AdresId");

                    b.HasIndex("GeboorteplaatsId");

                    b.HasIndex("LoginNaam")
                        .IsUnique();

                    b.HasIndex("TaalId");

                    b.ToTable("Personen");

                    b.HasDiscriminator<string>("PersoonType").HasValue("Persoon");
                });

            modelBuilder.Entity("Model.Entities.ProfielInteresse", b =>
                {
                    b.Property<int>("PersoonId")
                        .HasColumnType("int");

                    b.Property<int>("InteresseSoortId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Aangepast")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ProfielInteresseTekst")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ProfielPersoonId")
                        .HasColumnType("int");

                    b.HasKey("PersoonId", "InteresseSoortId");

                    b.HasIndex("InteresseSoortId");

                    b.HasIndex("ProfielPersoonId");

                    b.ToTable("ProfielInteresses");
                });

            modelBuilder.Entity("Model.Entities.Provincie", b =>
                {
                    b.Property<int>("ProvincieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ProvincieCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("ProvincieNaam")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ProvincieId");

                    b.HasIndex("ProvincieCode")
                        .IsUnique();

                    b.HasIndex("ProvincieNaam")
                        .IsUnique();

                    b.ToTable("Provincies");

                    b.HasData(
                        new
                        {
                            ProvincieId = 1,
                            ProvincieCode = "ANT",
                            ProvincieNaam = "Antwerpen"
                        },
                        new
                        {
                            ProvincieId = 2,
                            ProvincieCode = "LIM",
                            ProvincieNaam = "Limburg"
                        },
                        new
                        {
                            ProvincieId = 3,
                            ProvincieCode = "OVL",
                            ProvincieNaam = "Oost-Vlaanderen"
                        },
                        new
                        {
                            ProvincieId = 4,
                            ProvincieCode = "VBR",
                            ProvincieNaam = "Vlaams-Brabant"
                        },
                        new
                        {
                            ProvincieId = 5,
                            ProvincieCode = "WVL",
                            ProvincieNaam = "West-Vlaanderen"
                        },
                        new
                        {
                            ProvincieId = 6,
                            ProvincieCode = "WBR",
                            ProvincieNaam = "Waals-Brabant"
                        },
                        new
                        {
                            ProvincieId = 7,
                            ProvincieCode = "HEN",
                            ProvincieNaam = "Henegouwen"
                        },
                        new
                        {
                            ProvincieId = 8,
                            ProvincieCode = "LUI",
                            ProvincieNaam = "Luik"
                        },
                        new
                        {
                            ProvincieId = 9,
                            ProvincieCode = "LUX",
                            ProvincieNaam = "Luxemburg"
                        },
                        new
                        {
                            ProvincieId = 10,
                            ProvincieCode = "NAM",
                            ProvincieNaam = "Naman"
                        },
                        new
                        {
                            ProvincieId = 11,
                            ProvincieCode = "BRU",
                            ProvincieNaam = "Brussel"
                        });
                });

            modelBuilder.Entity("Model.Entities.Straat", b =>
                {
                    b.Property<int>("StraatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("GemeenteId")
                        .HasColumnType("int");

                    b.Property<string>("StraatNaam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StraatId");

                    b.HasIndex("GemeenteId");

                    b.HasIndex("StraatNaam")
                        .IsUnique();

                    b.HasIndex("StraatId", "StraatNaam")
                        .IsUnique();

                    b.ToTable("Straten");

                    b.HasData(
                        new
                        {
                            StraatId = 1,
                            GemeenteId = 1730,
                            StraatNaam = "Abelenstraat"
                        },
                        new
                        {
                            StraatId = 2,
                            GemeenteId = 1730,
                            StraatNaam = "Dorpstraat"
                        },
                        new
                        {
                            StraatId = 3,
                            GemeenteId = 1730,
                            StraatNaam = "Marktplaats"
                        },
                        new
                        {
                            StraatId = 4,
                            GemeenteId = 1731,
                            StraatNaam = "Anjerstraat"
                        },
                        new
                        {
                            StraatId = 5,
                            GemeenteId = 1731,
                            StraatNaam = "Bloemenstraat"
                        },
                        new
                        {
                            StraatId = 6,
                            GemeenteId = 1732,
                            StraatNaam = "Alexstraat"
                        },
                        new
                        {
                            StraatId = 7,
                            GemeenteId = 1732,
                            StraatNaam = "Bartstraat"
                        },
                        new
                        {
                            StraatId = 8,
                            GemeenteId = 1790,
                            StraatNaam = "Corneelstraat"
                        },
                        new
                        {
                            StraatId = 9,
                            GemeenteId = 1790,
                            StraatNaam = "Davidstraat"
                        },
                        new
                        {
                            StraatId = 10,
                            GemeenteId = 1790,
                            StraatNaam = "Eikenstraat"
                        },
                        new
                        {
                            StraatId = 11,
                            GemeenteId = 1791,
                            StraatNaam = "Fanfarestraat"
                        },
                        new
                        {
                            StraatId = 12,
                            GemeenteId = 1791,
                            StraatNaam = "Geelstraat"
                        },
                        new
                        {
                            StraatId = 13,
                            GemeenteId = 1792,
                            StraatNaam = "Hamstraat"
                        },
                        new
                        {
                            StraatId = 14,
                            GemeenteId = 1792,
                            StraatNaam = "Imkerstraat"
                        },
                        new
                        {
                            StraatId = 15,
                            GemeenteId = 1793,
                            StraatNaam = "Jurgenstraat"
                        },
                        new
                        {
                            StraatId = 16,
                            GemeenteId = 1793,
                            StraatNaam = "Kimstraat"
                        },
                        new
                        {
                            StraatId = 17,
                            GemeenteId = 1793,
                            StraatNaam = "Langestraat"
                        });
                });

            modelBuilder.Entity("Model.Entities.Taal", b =>
                {
                    b.Property<int>("TaalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("TaalCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("TaalNaam")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TaalId");

                    b.HasIndex("TaalNaam")
                        .IsUnique();

                    b.ToTable("Talen");

                    b.HasData(
                        new
                        {
                            TaalId = 1,
                            TaalCode = "nl",
                            TaalNaam = "Nederlands"
                        },
                        new
                        {
                            TaalId = 2,
                            TaalCode = "fr",
                            TaalNaam = "Frans"
                        },
                        new
                        {
                            TaalId = 3,
                            TaalCode = "en",
                            TaalNaam = "Engels"
                        });
                });

            modelBuilder.Entity("Model.Entities.Medewerker", b =>
                {
                    b.HasBaseType("Model.Entities.Persoon");

                    b.Property<int?>("AfdelingId")
                        .HasColumnType("int");

                    b.Property<int>("AfdelingsId")
                        .HasColumnType("int");

                    b.HasIndex("AfdelingId");

                    b.ToTable("Personen");

                    b.HasDiscriminator().HasValue("M");

                    b.HasData(
                        new
                        {
                            PersoonId = 1,
                            AdresId = 1,
                            FamilieNaam = "Jansen",
                            Geblokkeerd = false,
                            GeboorteDatum = new DateTime(2000, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeboorteplaatsId = 1790,
                            GeslachtType = 0,
                            LoginAantal = 0,
                            LoginNaam = "Jan",
                            LoginPaswoord = "Baarden",
                            TaalId = 1,
                            TelefoonNr = "011/111111",
                            VerkeerdeLoginsAantal = 0,
                            VoorNaam = "Jan",
                            AfdelingsId = 1
                        },
                        new
                        {
                            PersoonId = 2,
                            AdresId = 1,
                            FamilieNaam = "Pieters",
                            Geblokkeerd = false,
                            GeboorteDatum = new DateTime(2000, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeboorteplaatsId = 1790,
                            GeslachtType = 0,
                            LoginAantal = 0,
                            LoginNaam = "Piet",
                            LoginPaswoord = "Baarden",
                            TaalId = 1,
                            TelefoonNr = "012/222222",
                            VerkeerdeLoginsAantal = 0,
                            VoorNaam = "Piet",
                            AfdelingsId = 1
                        },
                        new
                        {
                            PersoonId = 3,
                            AdresId = 1,
                            FamilieNaam = "Jorissen",
                            Geblokkeerd = false,
                            GeboorteDatum = new DateTime(2001, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeboorteplaatsId = 1790,
                            GeslachtType = 0,
                            LoginAantal = 0,
                            LoginNaam = "Joris",
                            LoginPaswoord = "Baarden",
                            TaalId = 1,
                            TelefoonNr = "013/333333",
                            VerkeerdeLoginsAantal = 0,
                            VoorNaam = "Joris",
                            AfdelingsId = 1
                        },
                        new
                        {
                            PersoonId = 4,
                            AdresId = 1,
                            FamilieNaam = "Korneels",
                            Geblokkeerd = false,
                            GeboorteDatum = new DateTime(2002, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GeboorteplaatsId = 1790,
                            GeslachtType = 0,
                            LoginAantal = 0,
                            LoginNaam = "Korneel",
                            LoginPaswoord = "Baarden",
                            TaalId = 1,
                            TelefoonNr = "014/444444",
                            VerkeerdeLoginsAantal = 0,
                            VoorNaam = "Korneel",
                            AfdelingsId = 1
                        });
                });

            modelBuilder.Entity("Model.Entities.Profiel", b =>
                {
                    b.HasBaseType("Model.Entities.Persoon");

                    b.Property<string>("BeroepTekst")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatieTijdstip")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAdres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FacebookNaam")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FirmaNaam")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("GoedgekeurdTijdstip")
                        .HasColumnType("datetime2");

                    b.Property<string>("KenningsmakingTekst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LaatsteUpdateTijdstip")
                        .HasColumnType("datetime2");

                    b.Property<string>("WebsiteAdres")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("WoontHierSindsDatum")
                        .HasColumnType("datetime2");

                    b.ToTable("Personen");

                    b.HasDiscriminator().HasValue("P");
                });

            modelBuilder.Entity("Model.Entities.Adres", b =>
                {
                    b.HasOne("Model.Entities.Straat", "Straat")
                        .WithMany("Adressen")
                        .HasForeignKey("StraatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Straat");
                });

            modelBuilder.Entity("Model.Entities.Bericht", b =>
                {
                    b.HasOne("Model.Entities.BerichtType", "BerichtType")
                        .WithMany("Berichten")
                        .HasForeignKey("BerichtTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entities.Gemeente", "Gemeente")
                        .WithMany()
                        .HasForeignKey("GemeenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entities.Bericht", "HoofdBericht")
                        .WithMany("Berichten")
                        .HasForeignKey("HoofdBerichtId");

                    b.HasOne("Model.Entities.Persoon", "Persoon")
                        .WithMany()
                        .HasForeignKey("PersoonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entities.Profiel", null)
                        .WithMany("Berichten")
                        .HasForeignKey("ProfielPersoonId");

                    b.Navigation("BerichtType");

                    b.Navigation("Gemeente");

                    b.Navigation("HoofdBericht");

                    b.Navigation("Persoon");
                });

            modelBuilder.Entity("Model.Entities.Gemeente", b =>
                {
                    b.HasOne("Model.Entities.Gemeente", "HoofdGemeente")
                        .WithMany("Gemeentes")
                        .HasForeignKey("HoofdGemeenteId");

                    b.HasOne("Model.Entities.Provincie", "Provincie")
                        .WithMany("Gemeentes")
                        .HasForeignKey("ProvincieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entities.Taal", "Taal")
                        .WithMany("Gemeentes")
                        .HasForeignKey("TaalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoofdGemeente");

                    b.Navigation("Provincie");

                    b.Navigation("Taal");
                });

            modelBuilder.Entity("Model.Entities.Persoon", b =>
                {
                    b.HasOne("Model.Entities.Adres", "Adres")
                        .WithMany("Personen")
                        .HasForeignKey("AdresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entities.Gemeente", "Gemeente")
                        .WithMany("Personen")
                        .HasForeignKey("GeboorteplaatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entities.Taal", "Taal")
                        .WithMany("Personen")
                        .HasForeignKey("TaalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adres");

                    b.Navigation("Gemeente");

                    b.Navigation("Taal");
                });

            modelBuilder.Entity("Model.Entities.ProfielInteresse", b =>
                {
                    b.HasOne("Model.Entities.InteresseSoort", "InteresseSoort")
                        .WithMany("ProfielInteresses")
                        .HasForeignKey("InteresseSoortId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entities.Persoon", "Persoon")
                        .WithMany()
                        .HasForeignKey("PersoonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entities.Profiel", null)
                        .WithMany("ProfielInteresses")
                        .HasForeignKey("ProfielPersoonId");

                    b.Navigation("InteresseSoort");

                    b.Navigation("Persoon");
                });

            modelBuilder.Entity("Model.Entities.Straat", b =>
                {
                    b.HasOne("Model.Entities.Gemeente", "Gemeente")
                        .WithMany("Straten")
                        .HasForeignKey("GemeenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gemeente");
                });

            modelBuilder.Entity("Model.Entities.Medewerker", b =>
                {
                    b.HasOne("Model.Entities.Afdeling", "Afdeling")
                        .WithMany("Medewerkers")
                        .HasForeignKey("AfdelingId");

                    b.Navigation("Afdeling");
                });

            modelBuilder.Entity("Model.Entities.Adres", b =>
                {
                    b.Navigation("Personen");
                });

            modelBuilder.Entity("Model.Entities.Afdeling", b =>
                {
                    b.Navigation("Medewerkers");
                });

            modelBuilder.Entity("Model.Entities.Bericht", b =>
                {
                    b.Navigation("Berichten");
                });

            modelBuilder.Entity("Model.Entities.BerichtType", b =>
                {
                    b.Navigation("Berichten");
                });

            modelBuilder.Entity("Model.Entities.Gemeente", b =>
                {
                    b.Navigation("Gemeentes");

                    b.Navigation("Personen");

                    b.Navigation("Straten");
                });

            modelBuilder.Entity("Model.Entities.InteresseSoort", b =>
                {
                    b.Navigation("ProfielInteresses");
                });

            modelBuilder.Entity("Model.Entities.Provincie", b =>
                {
                    b.Navigation("Gemeentes");
                });

            modelBuilder.Entity("Model.Entities.Straat", b =>
                {
                    b.Navigation("Adressen");
                });

            modelBuilder.Entity("Model.Entities.Taal", b =>
                {
                    b.Navigation("Gemeentes");

                    b.Navigation("Personen");
                });

            modelBuilder.Entity("Model.Entities.Profiel", b =>
                {
                    b.Navigation("Berichten");

                    b.Navigation("ProfielInteresses");
                });
#pragma warning restore 612, 618
        }
    }
}
